### ISSUE TITLE
Couldn't get it to work

### ISSUE THREAD

**Issue by petenice** [matfish2/craft-optimum#1]
Tried to get this up and running to no avail. I'm on CraftCMS 4.3.6.1. 

I could set up experiments in the CP, and I tried variations on the following template code, but never saw the experiment change on reload, nor did I see different options coming through the includes.

<h1>Experiment Here</h1>
{% optimum 'homeButton' %}
  <p>original</p>
    {% include '_optimum/homeButton/yellow.twig' %} 
  {% include '_optimum/homeButton/red.twig' %} 
{% endoptimum %}

{% optimum 'cta_position' 'top' %}
   <button>Buy now TOP!</button>
{% endoptimum %}
{% optimum 'cta_position' 'original' %}
   <button>Buy now ORIG!</button>  
{% endoptimum %}
{% optimum 'cta_position' 'bottom' %}
   <button>Buy now Bottom!</button>
{% endoptimum %}

**Comment by matfish2** [comment]
@petenice thank you for reporting this.
1. Did you check the troubleshooting section? https://github.com/matfish2/craft-optimum#troubleshooting
2. Can you please include the experiment settings from the CP
3. Can you please check if there is an optimum_{experiment} cookie on the page? If so, what is the value?
4. Can you share to content of the compiled view?

**Comment by matfish2** [comment]
1. There is no need to add the includes explicitly. Optimum automatically loads them when applicable.
```
{% optimum 'homeButton' %}
original
{% endoptimum %}
```
2. For page to load different variations you'd need to delete the `optimum_homeButton` cookie, which is used to provide a consistent experience per user.
![Screenshot 2023-07-11 093405](https://github.com/matfish2/craft-optimum/assets/1510460/71506ab6-cb45-43b2-b877-d7d0521703d8)

**Comment by matfish2** [comment]
> Multiple experiments on the same page are currently not supported. I'm working to enable.
Now enabled in v1.1.0

**Comment by petenice** [comment]
Huzzah! I get it now, Optimum automatically loads the experiments based on the path name. That's neato burrito. Thanks very much for your help!
