### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by wakeuphate** [matfish2/craft-optimum#3]
During installation Optimum seems to fail while trying to create the `sm_optimum_experiments` table.

```
*** failed to install optimum: An error occurred while executing the "matfish\Optimum\migrations\Install migration: SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "enabled" is of type boolean but default expression is of type integer
HINT:  You will need to rewrite or cast the expression.
The SQL being executed was: CREATE TABLE "sm_optimum_experiments" (
	"id" serial NOT NULL PRIMARY KEY,
	"name" varchar(255) NOT NULL UNIQUE,
	"handle" varchar(255) NOT NULL UNIQUE,
	"startAt" timestamp(0) NULL DEFAULT NULL,
	"endAt" timestamp(0) NULL DEFAULT NULL,
	"enabled" boolean DEFAULT 0,
	"dateCreated" timestamp(0),
	"dateUpdated" timestamp(0)
)
```

It seems that @ https://github.com/matfish2/craft-optimum/blob/0c2106e0f9bfe664e481820c646a3ee15d078dc4/src/migrations/Install.php#L21 this should be `'enabled' => $this->boolean()->defaultValue(false),`

I was going to create a PR to change this but I assume it has been working previously so perhaps it's a MySQL vs Postgres issue and needs more attention than I could give it.

**Comment by matfish2** [comment]
@wakeuphate that you for reporting and debugging this!

Can you please try the latest version (1.2.1) and let me know if the issue was resolved.

**Comment by wakeuphate** [comment]
@matfish2 looks to have worked just fine, thanks for the quick response!
