### ISSUE TITLE
Integrity constraint violation: problem with handle field after soft-deleting experiments

### ISSUE THREAD

**Issue by birdkiwi** [matfish2/craft-optimum#4]
Hi!
I found a issue with your plugin. 
After deleting Experiment in CP and creating it again with the same handle it throws error below:
![2023-09-19_16-34-36](https://github.com/matfish2/craft-optimum/assets/3119744/17ab6100-48f7-40dc-89ac-65133d1c6097)

I have some thoughts how it could be fixed:
1. I think we need to listen to `EVENT_AFTER_DELETE_ELEMENT` and check `hardDelete` flag
2. Don't forget to delete entries from `craft_optimum_experiment_variants` and `craft_optimum_experiments` after hardDelete.
3. It's better to check if handle is present in soft-deleted Experiments and warn user in CP instead of throwing DB exceptions

**Comment by matfish2** [comment]
Hi @birdkiwi 
Thank you for reporting and for you suggestions.
I'm surprised that it soft deletes in the first place. Wasn't aware that this was the default behaviour.
I'll change to hard delete and update on the issue once done

**Comment by matfish2** [comment]
Fixed in 1.2.2
