### ISSUE TITLE
Only showing one variant

### ISSUE THREAD

**Issue by LinneaHarts** [matfish2/craft-optimum#5]
I set up my first experiment and it's only ever showing one variant (bestAvailable). I have tried:
1. Setting the percentage on that variant to be very low
2. Adding both options as variants rather than original
3. Switching from A to B verion of including optimum
4. Clearing all craft caches
5. Viewing the page in a different browser and or incognito mode

This is on Craft 4.5.5. Here is a screenshot of the experiment setup
![Screenshot 2023-10-10 at 17 10 51](https://github.com/matfish2/craft-optimum/assets/25594826/9a7c00a3-54d9-4b86-8c9c-b7f47a30bd65)

And here is the code I'm currently using:
```
{% optimum 'buyTickets' 'original' %}
                          Original
                        {% endoptimum %}
                        {% optimum 'buyTickets' 'syos' %}
                          SYOS
                        {% endoptimum %}
                        {% optimum 'buyTickets' 'bestAvailable' %}
                          Best Available
                        {% endoptimum %}
```

**Comment by matfish2** [comment]
@LinneaHarts thanks for reporting.

1. Can you please check if there is an `optimum` cookie (should be `optimum_{experiment}`) on the page and what is it's value?

2. Can you please try passing another variant explicitly using ?optimum={variant}, e.g `optimum=syos`

**Comment by matfish2** [comment]
Also, I see the end date is set to 11/09/2023
I assume that's in MM/DD/YYYY format as plugin wouldn't allow saving a date in the past.
Nevertheless can you please check the `optimum_experiments.ends_at` column and confirm the date is saved correctly?
Can you please try to remove the end date and see if the issue persists?

**Comment by LinneaHarts** [comment]
Thank you for the prompt response!

Updating the end date to 2024 fixed my issue. However, the 2023 date was what it defaulted to, as a month from the day that I set up the test, so I wonder if there is a tiny bug with the default. Thanks!

**Comment by matfish2** [comment]
@LinneaHarts I'm thinking it has something to do with the date format. Maybe the system saved it as Sep 11 rather than 9 Nov? 
Could be related to https://github.com/matfish2/craft-optimum/issues/2
Can you please check what is the date format on your Craft installation?

**Comment by LinneaHarts** [comment]
Sorry, I think I confused myself and thought it was already 2024 🤪 

My date format is MM/DD/YYYY. So it does sound like the plugin is interpretting all dates as DD/MM/YYYY since it fixed it when I pushed the date out into 2024. It is popping up the right calendar selector. 
![Screenshot 2023-10-11 at 14 06 13](https://github.com/matfish2/craft-optimum/assets/25594826/faf9b434-239a-4524-bf04-58072b54452f)

**Comment by matfish2** [comment]
The plugin uses Craft's `DatetimeHelper` to interpret the date sent from the front-end, so should work well with all date formats.

See ExperimentsController:157:
```
 $value = DateTimeHelper::toDateTime($value)->format('Y-m-d H:i:s');
```

Locally I can confirm it is saved correctly. If you have access to the database you can check what is the `endAt` value
```
select * from mf_optimum_experiments
```

**Comment by LinneaHarts** [comment]
It is set correctly in the database. Now I'm not sure why pushing out the date helped. I'm sorry if I wasted your time on this. I'll reopen if I encounter this again.
