### ISSUE TITLE
PostgresQL errors

### ISSUE THREAD

**Issue by eve-prefix** [matfish2/craft-optimum#9]
Getting some errors using a new install of Optimum with Craft using PostgresQL. This is when creating a new experiment.

```
SQLSTATE[42703]: Undefined column: 7 ERROR: column "experimentid" does not exist
LINE 1: DELETE FROM "optimum_experiment_variants" WHERE experimentId...
^
HINT: Perhaps you meant to reference the column "optimum_experiment_variants.experimentId".
The SQL being executed was: DELETE FROM "optimum_experiment_variants" WHERE experimentId=134509 AND id NOT IN (134510,134511)
```

Changing [this line](https://github.com/matfish2/craft-optimum/blob/main/src/controllers/ExperimentsController.php#L231) to the following fixed it (add square brackets around column name):

```
        \matfish\Optimum\records\Variant::deleteAll("[[experimentId]]={$this->experiment->id} AND id NOT IN ({$newIds})");
```

Also when re-saving an existing experiment (without making any changes at all) generated this error:
```
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: ` integer
LINE 3: WHERE ("optimum_experiments"."handle"=$1) AND (`id` != $2))
^
HINT: No operator matches the given name and argument type. You might need to add an explicit type cast.
The SQL being executed was: SELECT EXISTS(SELECT *
FROM "optimum_experiments"
WHERE ("optimum_experiments"."handle"='demoExperiment') AND (`id` != 134506))
```

Fix for this was to remove the backticks from lines 33 and 42 [here](https://github.com/matfish2/craft-optimum/blob/main/src/elements/Experiment.php).

Craft: Craft Pro 4.5.11.1
Optimum: 1.3.1

**Comment by matfish2** [comment]
Thanks for reporting @eve-prefix 
Fixed in `1.4.0`
